name: CI Workflow
run-name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci-pipeline:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verify Git Repository
        run: |
          git status
          git log --oneline

      - name: Install Python
        run: |
          sudo yum update -y
          sudo yum install python3 -y
          sudo yum install -y python3-pip

          python3 -m pip install --upgrade pip
          pip install pytest requests mysql-connector-python

      - name: Install Docker
        run: |
          sudo yum install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER
          newgrp docker
          sudo chmod 666 /var/run/docker.sock

      - name: Run Unit Tests
        run: pytest db_app/test_users.py

      - name: Build Docker Image
        run: |
          docker build -t python-app ./db_app
          docker images

      - name: Run Integration Tests
        uses: ./.github/actions/integration
        with:
          skip_checkout: 'true'

      - name: Bump Version
        uses: ./.github/actions/version-bump
        with:
          version_type: 'patch'
          git_user_name: 'yafit89'
          git_user_email: 'yafitt364@gmail.com'
        env:
          GIT_PAT: ${{ secrets.GIT_PAT }}